markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "PMO PlanetScience"
markdown: kramdown

author: "PMO"
atom-baseurl: "http://planetscience.github.io"

navigations:
  - title: Blog Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Github
    class: fa fa-film
    href: https://github.com/planetscience
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

